In [2]:
import numpy as np

In [3]:
cond1 = np.array([True, False, True])

In [4]:
s = 1 * cond1

In [5]:
s

array([1, 0, 1])

In [6]:
cond2 = np.array([False, False, True])

In [7]:
# OR Operation
cond1 | cond2

array([ True, False,  True], dtype=bool)

In [8]:
# Inverse Operation
~ (cond1 | cond2)

array([False,  True, False], dtype=bool)

In [10]:
# Multiply 3 to the result
3 * ~ (cond1 | cond2)

array([0, 3, 0])

In [16]:
result = 1 * cond1 + 2 * cond2 + 3 * ~ (cond1 | cond2)

In [17]:
result

array([1, 3, 3])

In [18]:
a = 1 * 1 + 2 * 0 + 3 * 1

In [19]:
a

4

In [35]:
arr = np.random.randn(3,3)

In [36]:
arr

array([[ 0.4301407 , -1.77113831, -0.30988789],
       [ 1.35064927, -1.47597874,  1.33057175],
       [ 0.81622174,  0.62255129,  0.56412735]])

In [43]:
sort_c = np.sort(arr,1) ## Sorting along the columns

In [44]:
sort_r = np.sort(arr,0) ## Sorting along the rows

In [41]:
np.save('sorted_array', np.sort(arr,0))

In [42]:
np.load('sorted_array.npy')

array([[ 0.4301407 , -1.77113831, -0.30988789],
       [ 0.81622174, -1.47597874,  0.56412735],
       [ 1.35064927,  0.62255129,  1.33057175]])

In [45]:
### You can save multiple arrays in a zip archive using np.savez and passing the arrays as key-word arguments

In [46]:
np.savez('array_archive.npz', a=sort_c, b=sort_r)

In [47]:
arch = np.load('array_archive.npz')

In [48]:
arch['a']

array([[-1.77113831, -0.30988789,  0.4301407 ],
       [-1.47597874,  1.33057175,  1.35064927],
       [ 0.56412735,  0.62255129,  0.81622174]])

In [50]:
np.sort(arr,1)

array([[-1.77113831, -0.30988789,  0.4301407 ],
       [-1.47597874,  1.33057175,  1.35064927],
       [ 0.56412735,  0.62255129,  0.81622174]])

In [51]:
arch['b']

array([[ 0.4301407 , -1.77113831, -0.30988789],
       [ 0.81622174, -1.47597874,  0.56412735],
       [ 1.35064927,  0.62255129,  1.33057175]])

In [52]:
np.sort(arr,0)

array([[ 0.4301407 , -1.77113831, -0.30988789],
       [ 0.81622174, -1.47597874,  0.56412735],
       [ 1.35064927,  0.62255129,  1.33057175]])