In [38]:
import numpy as np

In [39]:
data = np.arange(10)

In [40]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
data[5]

5

In [42]:
data[5:8]

array([5, 6, 7])

In [43]:
data[5:7] = 12

In [44]:
data

array([ 0,  1,  2,  3,  4, 12, 12,  7,  8,  9])

In [45]:
### As you can see, if we assign a scalar value to a slice .i.e [5:7], the value is propogated to the entire selection
### This is called "Broadcasting" which comes into picture when performing operations between differently sized arrays or
### scalars and arrays


In [46]:
### Slices are array views on the original array. This is an important distinction between an array and a list
### This means that data is not copied, and any modifications to the view will be reflected in the source array
### as you just saw in the example abobe. When the view data[5:7] was modified, the original array was modified too
### as you will see

data

array([ 0,  1,  2,  3,  4, 12, 12,  7,  8,  9])

In [47]:
### This is a very powerful and unique feature of NumPy. NumPy was designed with large dataset cases in mind.
### Imagine the performance and memory problems if NumPy insisted on copying data everytime a view is created.
### In most other programming languages, in array operations, copying is done.

In [48]:
### If you want to copy a slice of an ndarray, instead of a view

data_slice = data[5:7].copy()

In [49]:
data_slice


array([12, 12])

In [50]:
##############################################################################################################################

In [51]:
### With higher dimensional arrays, you have many more options.

### In a multidimensional array, the elements of each index are no longer scalars but rather one-dimensional arrays

In [52]:
arr2d = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [53]:
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [54]:
arr2d[2]

array([5, 6, 7])

In [55]:
### Individual elements can be accessed as follows

In [56]:
arr2d[1,2]

5

In [57]:
### Here 1 is the index on axis 0 (rows) and 1 is the index on axis 1 (columns) .. 1 is the second row. 2 is the thrid column
### indexing starts with 0

In [59]:
### The same element can be also accessed as 
arr2d[1][2]

5

In [60]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,6,7]]])

In [61]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr3d[1]

array([[7, 8, 9],
       [3, 6, 7]])

In [64]:
arr3d.shape

(2, 2, 3)

In [65]:
### The shape says that there are 2 internal 2x3 arrays. So 0 is gonna return the first 2x3 array and 1 is gonna return the next

In [66]:
rea_vals = arr3d[0].copy()

In [67]:
arr3d[0] = 11

In [68]:
arr3d

array([[[11, 11, 11],
        [11, 11, 11]],

       [[ 7,  8,  9],
        [ 3,  6,  7]]])

In [69]:
arr3d

array([[[11, 11, 11],
        [11, 11, 11]],

       [[ 7,  8,  9],
        [ 3,  6,  7]]])

In [70]:
arr3d[0] = rea_vals

In [71]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [72]:
### Now lets try another form of indexing

arr3d[1,0] ### Now this shoudl return the second 2x3 array and the first element in it which is an array in itself

array([7, 8, 9])

In [73]:
arr3d[1,1]

array([3, 6, 7])

In [74]:
### Now lets see indexing with slices


In [76]:
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [80]:
arr2d[1:,:2]

array([[3, 4],
       [5, 6]])

In [ ]:
### Slicing starts with 1 and not 0 as in indexes

### The above statement is gonna return everything except the first row (as stated by 1:) and the first 2 columns (as stated by :2)



In [81]:
arr2d[1:,:1]

array([[3],
       [5]])

In [82]:
### The example above ought to explain it better

In [83]:
### A little recap of Python slicing
"""
a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1
a[:]         # a copy of the whole array
"""

'\na[start:end] # items start through end-1\na[start:]    # items start through the rest of the array\na[:end]      # items from the beginning through end-1\na[:]         # a copy of the whole array\n'

In [84]:
### We can also mix index and slices together

arr2d[1, :2]

array([3, 4])

In [ ]:
### Here, 1 referes to the index 1 on axis 0 and :2 denotes the first 2 columns

In [86]:
arr2d[:,:1]

array([[1],
       [3],
       [5]])

In [ ]:
### A colon by itself means to take the entire axis

In [ ]:
### Refer pdf for more info on Boolean indexing and fancy indexing