In [55]:
import numpy as np
first_array = np.array([1,2,3,4,5])

In [56]:
first_array

array([1, 2, 3, 4, 5])

In [58]:
# Multi-dimensional arrays can be created as follows:
a = [1, 2, 3, 4, 5]
b = [1,4,9,16,25]
squares = np.array([a,b])
print(squares)

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]


In [59]:
squares.dtype

dtype('int32')

In [61]:
# Creating a 3-dimensional array
# We can use the same lists again and add an additional dimensional array to it.
cubes = np.array([[a,b,[1,8,27,64,225]]])
cubes.ndim

3

In [63]:
# Accessing the elements using indexing
cubes[0][1]

array([ 1,  4,  9, 16, 25])

In [18]:
a = np.array([1,2,3,4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
# Get the type of a 
type(a)

numpy.ndarray

In [8]:
# Convert to list
b = a.tolist()

In [15]:
type(b)

list

In [21]:
a[0] = 5.6

In [22]:
a

array([5, 2, 3, 4])

In [11]:
a = [1, 2, 3, 4, 5]
b = [1,4,9,16,25]
squares = np.array([a,b])

In [13]:
sq_list = squares.tolist()

In [14]:
sq_list

[[1, 2, 3, 4, 5], [1, 4, 9, 16, 25]]

In [24]:
# Create a numpy array from a random set of integers
rand_arr = np.random.randint(100, size=(6, 6))
print(rand_arr)

[[14 36 45 51 94 59]
 [22 76 84 16 77 36]
 [ 4 62 76 45 32 94]
 [77 22 84 56 47 82]
 [18 54 10 86 88 81]
 [86 32  2 96 82 33]]


In [27]:
rand_arr[0,3:5] # get only the column 3 through 4 from row 0

array([51, 94])

In [28]:
# Get the elements at the bottom right corner
rand_arr[4:,4:]

array([[88, 81],
       [82, 33]])

In [29]:
# Get a complete row
rand_arr[2,:] # the 3rd row .. i.e index 2

array([ 4, 62, 76, 45, 32, 94])

In [30]:
# Get a complete row 
rand_arr[:,3] # the 4th row.. i.e index 3

array([51, 16, 45, 56, 86, 96])

In [43]:
rand_arr[::2] # Getting alternative rows

array([[14, 36, 45, 51, 94, 59],
       [ 4, 62, 76, 45, 32, 94],
       [18, 54, 10, 86, 88, 81]])

In [46]:
rand_arr[:,::2] # Getting alternate columns

array([[14, 45, 94],
       [22, 84, 77],
       [ 4, 76, 32],
       [77, 84, 47],
       [18, 10, 88],
       [86,  2, 82]])

In [47]:
# Lets print random array for the next exercise
rand_arr

array([[14, 36, 45, 51, 94, 59],
       [22, 76, 84, 16, 77, 36],
       [ 4, 62, 76, 45, 32, 94],
       [77, 22, 84, 56, 47, 82],
       [18, 54, 10, 86, 88, 81],
       [86, 32,  2, 96, 82, 33]])

In [52]:
rand_arr[2::2,::2]

array([[ 4, 76, 32],
       [18, 10, 88]])

### Broadcasting

In [49]:
# Lets create an array
a = np.array([1,2,34,5,563])

In [50]:
a

array([  1,   2,  34,   5, 563])

In [51]:
# Lets take a slice of a and assign it to b
b = a[2:5]

In [53]:
# Lets add an item to b's 0th index position
b[0] = 252

In [54]:
# But turns out a changed as well along with b
a

array([  1,   2, 252,   5, 563])

That is because slices are references and not separate objects and hence any change made through the references pointing to a slice of an array creates changes in the original array. This is called broadcasting.