In [1]:
### One of the key features of Numpy is its N-dimensional array object or ndarray.

### Its a fast, flexible container for large data sets in Python.
### Arrays enable us to perform mathematical operations on whole blocks of data using a syntax similar to equivalent 
### operations between scalar elements.

In [2]:
import numpy as np

In [4]:
data = np.arange(7)

In [9]:
data1 = np.array(data)

In [10]:
data1

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
data1 * 10

array([ 0, 10, 20, 30, 40, 50, 60])

In [14]:
data1 + data1

array([ 0,  2,  4,  6,  8, 10, 12])

In [15]:
### And ndarray is a generic multidimensional container for homogenous data
### All of the elements myst be of the same data type.

### Each array has a "shape", a tupe representing the size of each dimension

data1.shape

(7,)

In [16]:
### data1 is a one-dimensional ndarray

In [17]:
### It also has a dtype, an object describing the data type of the array

In [18]:
data1.dtype

dtype('int32')