In [1]:
import numpy as np

In [2]:
data = [6,7.5,3,-98]

In [3]:
### The easiest way to create an ndarray is to use the array function. 
### This accepts any sequence-like objects (including other arrays) and produces a new NumPy array
data

[6, 7.5, 3, -98]

In [5]:
arr = np.array(data)

In [6]:
arr

array([  6. ,   7.5,   3. , -98. ])

In [7]:
### Nested sequences like a list of equal length lists, will ne converted into a multidimensional array

data2 = [[1,2,3,4],[5,6,7,8]]

In [8]:
arr2 = np.array(data2)

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr2.dtype

dtype('int32')

In [13]:
### Unless explicitly specified, np.array tries to infer a good data type for the array it creates.
### The data is stored in the special dtype object

arr.dtype


dtype('float64')

In [14]:
### You can explictly choose the data type as well as shown below

arr3 = np.array([1,2,3], dtype=np.float64)

In [15]:
arr3

array([ 1.,  2.,  3.])

In [ ]:
### Dtypes are what make NumpY so powerful and flexible. In most cases they map directly onto an underlying machine representation,
### which makes it wasy to read and write binary streams of data to disk and also connect to code written in
### a low level language like C or Fortran.

### A standard double-precision floating point value (that's used under the hood in Python's float object)
### takes up 8 bytes or 64 bytes. Thus this ype is knows as float64 in NumPy.


In [16]:
### You can explicitly convert or cast an array from one dtype to another as follows

arr3.dtype

dtype('float64')

In [18]:
int_arr3 = arr3.astype(np.int32)

In [19]:
int_arr3

array([1, 2, 3])

In [20]:
int_arr3.dtype

dtype('int32')

In [24]:
arr4 = np.array([1,5.6,4,89])

In [25]:
### Lets create a float64 array and typecast it into an int array and see what happens
arr4

array([  1. ,   5.6,   4. ,  89. ])

In [26]:
arr4.dtype

dtype('float64')

In [27]:
int_arr4 = arr4.astype(np.int32)

In [28]:
int_arr4

array([ 1,  5,  4, 89])

In [29]:
### You dont necessarily need to mention int32 or float64 all the time .. For example, the above declaration can 
### also be written as

int_arr4 = arr4.astype(int)

In [30]:
int_arr4

array([ 1,  5,  4, 89])

In [31]:
int_arr4.dtype

dtype('int32')

In [ ]:
### NumPy is smart enough to alias the Python types to the equivalent dtypes

In [32]:
### Another special feature is that one array's dtype can be used on another

arr3.dtype

dtype('float64')

In [36]:
new_arr = np.arange(10)

In [37]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr.dtype

dtype('int32')

In [40]:
new_arr.astype(arr3.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [41]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### As you can see in the example above, the new_arr object gets the dtype of the arr3 object

### Also, calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old.

In [43]:
### There are shorthand type code strings that we can use to refer to a dtype

In [44]:
hello = np.array([1,2,3,4], dtype='u4')

In [45]:
hello.dtype

dtype('uint32')

In [ ]:
### Note that float32 and float64 are only capable of approximating fractional quantities.
### In complex computations, you may accrue some floating point error.