Python is convenient, but it can also be slow. However, it does allow you to access libraries that execute faster code written in languages like C. NumPy is one such library: it provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers - like matrices.

The most common way to work with numbers in NumPy is through ndarray objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, you can use ndarrays to represent any of the data types we covered before: scalars, vectors, matrices, or tensors. (Tensors are any n-dimensional data structures above 2 dimensions).

Scalars in NumPy are a bit more involved than in Python. Instead of Python’s basic types like int, float, etc., NumPy lets you specify signed and unsigned types, as well as different sizes. So instead of Python’s int, you have access to types like uint8, int8, uint16, int16, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a NumPy array, you can specify the type - but every item in the array must have the same type. In this regard, NumPy arrays are more like C arrays than Python lists.

In [1]:
import numpy as np

### Create your first array

In [3]:
first_array = np.array([1,2,3,4,5])

In [4]:
first_array

array([1, 2, 3, 4, 5])

In [5]:
# Get the type of the
type(first_array)

numpy.ndarray

In [6]:
# Convert to list
b = first_array.tolist()

In [12]:
type(b)

list

In [13]:
# Multi-dimensional arrays can be created as follows:
a = [1, 2, 3, 4, 5]
b = [1,4,9,16,25]
squares = np.array([a,b])
print(squares)

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]


In [14]:
squares.dtype # Get the data type of the array

dtype('int32')

In [15]:
# Creating a 3-dimensional array
# We can use the same lists again and add an additional dimensional array to it.
cubes = np.array([[a,b,[1,8,27,64,225]]])
cubes.ndim

3

### Accessing the elements using array indexing

In [16]:
cubes[0][1]

array([ 1,  4,  9, 16, 25])

In [17]:
# Create a numpy array from a random set of integers
rand_arr = np.random.randint(100, size=(6, 6))
print(rand_arr)

[[16 93 22 73 18 52]
 [82 96 24 85 87 20]
 [71  9 44 17 24 98]
 [ 7 89 13 10 89 96]
 [86 42 62 99 91 22]
 [81 24 68  3 73 61]]


In [18]:
rand_arr[0,3:5] # get only the column 3 through 4 from row 0

array([73, 18])

In [19]:
# Get the elements at the bottom right corner
rand_arr[4:,4:] # everything above index 4 (row 5&6 and column 5&6)

array([[91, 22],
       [73, 61]])

In [20]:
# Get a complete row
rand_arr[2,:] # the 3rd row .. i.e index 2

array([71,  9, 44, 17, 24, 98])

In [21]:
# Get a complete row 
rand_arr[:,3] # the 4th row.. i.e index 3

array([73, 85, 17, 10, 99,  3])

In [22]:
rand_arr[::2] # Getting alternative rows

array([[16, 93, 22, 73, 18, 52],
       [71,  9, 44, 17, 24, 98],
       [86, 42, 62, 99, 91, 22]])

### Broadcasting

In [2]:
# Lets create an array
a = np.array([1,2,34,5,563])

In [3]:
a

array([  1,   2,  34,   5, 563])

In [4]:
# Lets take a slice of a and assign it to b
b = a[2:5]

In [5]:
# Lets add an item to b's 0th index position
b[0] = 252

In [6]:
# But turns out a changed as well along with b
a

array([  1,   2, 252,   5, 563])

That is because slices are references and not separate objects and hence any change made through the references pointing to a slice of an array creates changes in the original array. This is called broadcasting.

In [7]:
b[0:2] = 1

In [8]:
a

array([  1,   2,   1,   1, 563])