One of the key features of Numpy is its N-dimensional array object called as ndarray. Its a fast, flexible container for large data sets in Python. Arrays enable us to perform mathematical operations on whole blocks of data using a syntax similar to equivalent. An ndarray is a generic multidimensional container for homogenous data. All of the elements myst be of the same data type.

Each array has a "shape", a tuple representing the size of each dimension


The following are some of the ways to create an ndarray

In [3]:
import numpy as np

#### Method 1
The simplest way is to use the array method.

##### To create a vector, you'd pass a Python list to the array function, like this:

In [48]:
data = [6,7.5,3,-98]
# Create a ndarray from the list
np_array = np.array(data)

In [16]:
data

[6, 7.5, 3, -98]

#### Method 2
Using asarray method.

In [17]:
data = [6,7.5,3,-98,7723,124]
np_array1 = np.array(data)

In [18]:
np_array1

array([  6.00000000e+00,   7.50000000e+00,   3.00000000e+00,
        -9.80000000e+01,   7.72300000e+03,   1.24000000e+02])

#### Method 3
Using arange

In [11]:
data = np.arange(7)

In [12]:
data

array([0, 1, 2, 3, 4, 5, 6])

#### Method 4 (from another ndarray)

In [13]:
data1 = np.array(data)

In [14]:
data1

array([0, 1, 2, 3, 4, 5, 6])

#### Method 5 (From Nested Sequences)
Ndarrays can also be created from nested sequences like a list of equal length lists.

In [19]:
data2 = [[1,2,3,4],[5,6,7,8]]
list_array = np.array(data2)

In [20]:
list_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Data Types in Ndarray

Unless explicitly specified, np.array tries to infer a good data type for the array it creates. The data is stored in the special dtype object. You can explictly choose the data type as well.

In [21]:
# though the elements are all integers, we can make them of type float
arr3 = np.array([1,2,3], dtype=np.float64)

In [22]:
arr3

array([ 1.,  2.,  3.])

The data type and dimensions of the ndarrays can be obtained as follows:

In [24]:
arr3.dtype

dtype('float64')

In [26]:
arr3.ndim

1

In [27]:
arr3.shape

(3L,)

In [28]:
# Lets get the dimension and shape of our list_array
list_array.ndim

2

In [29]:
list_array.shape

(2L, 4L)

dtypes are what that make NumPy so powerful and flexible. In most cases they map directly onto an underlying machine representation, which makes it wasy to read and write binary streams of data to disk and also connect to code written in a low level language like C or Fortran.

A standard double-precision floating point value (that's used under the hood in Python's float object) takes up 8 bytes or 64 bytes. Thus this type is known as float64 in NumPy.

### Casting one dtype array into another

In [31]:
int_arr3 = arr3.astype(np.int32)

In [32]:
int_arr3.dtype

dtype('int32')

We dont necessarily need to mention int32 or float64 all the time .. For example, the above declaration can also be written as


In [33]:
int_arr3 = arr3.astype(np.int)

In [34]:
int_arr3.dtype

dtype('int32')

NumPy is smart enough to alias the Python types to the equivalent dtypes. 

Another special feature is that one array's dtype can be used on another array to convert it.

In [39]:
new_arr = np.arange(10)

In [40]:
# Lets check its datatype
new_arr.dtype

dtype('int32')

It is of type int32. Now let's convert that into a float array using the dtype attribute of a float array we have - arr3

In [41]:
# Lets check arr3's dtype before we proceed ahead
arr3.dtype

dtype('float64')

In [45]:
# We can change the dtype of new_arr as follows:
new_arr = new_arr.astype(arr3.dtype)

In [46]:
new_arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [47]:
new_arr.dtype

dtype('float64')

### Some Unique Use Cases
#### Generate Multiple Random Numbers From The Normal Distribution

In [4]:
np.random.normal(size=4)

array([-0.62986076, -1.56676055,  0.99055557, -0.10473714])

#### Generate Four Random Numbers From The Uniform Distribution

In [5]:
np.random.uniform(size=4)

array([ 0.95333191,  0.01636087,  0.30438135,  0.68576288])

#### Generate Four Random Integers Between 1 and 100

In [6]:
np.random.randint(low=1, high=100, size=4)

array([41, 98, 26, 84])

#### Create an Array of Zeroes

In [9]:
npzeroes = np.zeros(6)
npzeroes

array([ 0.,  0.,  0.,  0.,  0.,  0.])

#### Create a range from 0 to 100

In [11]:
zero_to_99 = np.arange(0, 100)
zero_to_99

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Create 100 ticks between 0 and 1

In [12]:
zero_to_1 = np.linspace(0, 1, 100)
zero_to_1

array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525,  0.26262626,  0.27272727,  0.28282828,  0.29292929,
        0.3030303 ,  0.31313131,  0.32323232,  0.33333333,  0.34343434,
        0.35353535,  0.36363636,  0.37373737,  0.38383838,  0.39393939,
        0.4040404 ,  0.41414141,  0.42424242,  0.43434343,  0.44444444,
        0.45454545,  0.46464646,  0.47474747,  0.48484848,  0.49494949,
        0.50505051,  0.51515152,  0.52525253,  0.53535354,  0.54545455,
        0.55555556,  0.56565657,  0.57575758,  0.58585859,  0.5959596 ,
        0.60606061,  0.61616162,  0.62626263,  0.63636364,  0.64646465,
        0.65656566,  0.66666667,  0.67676768,  0.68686869,  0.69