### Accessing the elements using array Indexing and Slicing

#### Slicing
Lets have a little recap of Python slicing

1. a[start:end] # get all items from start through end-1

2. a[start:]    # get all items from start through the rest of the array

3. a[:end]      # get all items from the beginning through end-1

4. a[:]         # a copy of the whole array

5. a[start:end:step] # get all items from start through end-1 with steps

In [1]:
import numpy as np
a = np.arange(10)

In [2]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Simple indexing
a[5]

5

In [4]:
a[2:5]

array([2, 3, 4])

In [5]:
# Slicing creates a copy and it can be used to assign values
a[2:5] = 10

In [6]:
a

array([ 0,  1, 10, 10, 10,  5,  6,  7,  8,  9])

In [7]:
# Slicing can also be used to assign sequences of dimension that is equal to the slice 
a[2:5] = 2,3,4

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Important - Slices are views
Slices are array views on the original array. This means that any modifications to the view will be reflected in the source array as you just saw in the example above. When the view data[2:5] was modified, the original array was modified too.

### Also-
NumPy was designed with large dataset cases in mind. Imagine the performance and memory problems if NumPy insisted on copying data everytime a view is created. In most other programming languages, in array operations, copying is done. But in Numpy slices are only views.

In [9]:
# Lets create a 3-d array
import numpy as np
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,6,7]]])

In [10]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [11]:
arr3d.shape

(2, 2, 3)

Looking at the shape, we can say that it is made up of 2 internal 2x3 arrays

### Exercise

In [12]:
# Lets access the 2nd row of the first matrix.
# Answer please???