### Accessing the elements using array Indexing and Slicing

#### Slicing
Lets have a little recap of Python slicing

1. a[start:end] # get all items from start through end-1

2. a[start:]    # get all items from start through the rest of the array

3. a[:end]      # get all items from the beginning through end-1

4. a[:]         # a copy of the whole array

5. a[start:end:step] # get all items from start through end-1 with steps

In [2]:
import numpy as np
a = np.arange(10)

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Simple indexing
a[5]

5

In [27]:
a[2:5]

array([2, 3, 4])

In [30]:
# Slicing creates a copy and it can be used to assign values
a[2:5] = 10

In [31]:
a

array([ 0,  1, 10, 10, 10,  5,  6,  7,  8,  9])

In [32]:
# Slicing can also be used to assign sequences of dimension that is equal to the slice 
a[2:5] = 2,3,4

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Important - Slices are views
Slices are array views on the original array. This means that any modifications to the view will be reflected in the source array as you just saw in the example above. When the view data[2:5] was modified, the original array was modified too.

### Also-
NumPy was designed with large dataset cases in mind. Imagine the performance and memory problems if NumPy insisted on copying data everytime a view is created. In most other programming languages, in array operations, copying is done. But in Numpy slices are only views.

In [4]:
# Lets create a 3-d array
import numpy as np
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,6,7]]])

In [7]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [9]:
arr3d.shape

(2, 2, 3)

Looking at the shape, we can say that it is made up of 2 internal 2x3 arrays

### Exercise

In [8]:
# Lets access the 2nd row of the first matrix.
# Answer please???

In [11]:
matrix_1 = arr3d[0].copy()

In [12]:
matrix_1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
matrix_1 = 50

In [14]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [20]:
# Create a numpy array from a random set of integers
rand_arr = np.random.randint(100, size=(6, 6))
print(rand_arr)

[[52 11 13 42 82 45]
 [73  7 43 56 52 74]
 [57 19 82 36 30 77]
 [75 24 51 42 98 32]
 [28 78  8 59 28 95]
 [55 24 22 10 17 18]]


In [21]:
rand_arr[0,3:5] # get only the column 3 through 4 from row 0

array([42, 82])

In [22]:
# Get the elements at the bottom right corner
rand_arr[4:,4:]

array([[28, 95],
       [17, 18]])

In [23]:
# Get a complete row
rand_arr[2,:] # the 3rd row .. i.e index 2

array([57, 19, 82, 36, 30, 77])

In [24]:
# Get a complete row 
rand_arr[:,3] # the 4th row.. i.e index 3

array([42, 56, 36, 42, 59, 10])

In [25]:
rand_arr[::2] # Getting alternative rows

array([[52, 11, 13, 42, 82, 45],
       [57, 19, 82, 36, 30, 77],
       [28, 78,  8, 59, 28, 95]])

## Exercise Question #1
How did the code above work? What is the meaning behind the double colons "::"

#### Solution

The general way in which sequence slicing is done in Python is as follows array_var[start:end:step]. Any of the parameters can be dropped too. Hence, in this example rand_arr[::2] represents every second element starting with 0(default).

In [30]:
# More examples
rand_arr1 = np.random.randint(100, size=(10, 10))
print(rand_arr1)

[[85 65  7 60  6 51 77 22 27 58]
 [22  2 68 32 71 24  6 67 81 88]
 [14 27  0  3 94 78 83 13 32 33]
 [74 31 22 65 51 53  2 69 39 62]
 [13 90 19 14 92 24 22 24 30 26]
 [62 80  9 83 88 39 25 46 50 56]
 [77 58 34 85  3 78 31 24 88 14]
 [88  8 86 34  8  7 20  7  0 68]
 [82  1 78 84 92 58  7 19 27 50]
 [77  7  1  3 30 56 23 15 81 31]]


## Exercise Question #2

Get me every 3rd row starting from the 2nd row (i.e index 1)

### Solution

In [32]:
rand_arr1[1::3]

array([[22,  2, 68, 32, 71, 24,  6, 67, 81, 88],
       [13, 90, 19, 14, 92, 24, 22, 24, 30, 26],
       [88,  8, 86, 34,  8,  7, 20,  7,  0, 68]])

In [34]:
# Lets make our array bigger and question harder
rand_arr1 = np.random.randint(100, size=(20, 20))
print(rand_arr1)

[[51  7 71 19 73 51 55 70 73  7 80 72 19 36 17  7 23 41 27 99]
 [37 27 55 20 96 95 27 79  5 14 15 81 96 44 75 24 94 82 15 69]
 [77  6 92 75 29 79 44 31 57 91 54 68 77 84  8  0 13 59 30 85]
 [66 57 63 25  7 93 10  2 55 72 14 65 45 93 22 48 95 20 29 12]
 [17 98 41  8  9 39 11 10 56  4  2 57 10 56 96 14 38  9 49 15]
 [89 71 77 81 23 74 82 60 11  9 41 34 47 72 12 52 28 70 98 65]
 [55 54 51 82  9 43 20 14 44 22 24 55 97 39 70 15  3 82 24 91]
 [12 75 92 20 98 80 38 23 20 88 95 62 71 79 14 98  8 43 55 34]
 [99 91 87 80 58 49 27 57 45 16 10 61 15 55 56 70 60 70 16 40]
 [ 8  4 40 83 98 16  9 97 67 42 87 38 16 65 42 49 41 40 94  4]
 [23 56 36 27 16 68 48  9 28 53 57 32 30 39 83 31 25 28  3 86]
 [49 65 97 68 31 91 89 43 37 13 75 27 53 14 38 64 38 12 55 63]
 [77 16 41  5 23 70 97 60 20 52 54  2 26 20 36 81 17 45 33  9]
 [37  5 92  4 71 10 96 69 97 28 18 86 37 73 36 97 24 10 12 89]
 [53 96  7  5 86  9 73 23 24 17 43 57 40 41 19  9 57 92 20 92]
 [81 50 26 93  8 94 33 95 65 42  7 19 99 37 96 77 63 92

## Exercise Question #3

Get me every 3rd row starting from the 2nd row.

### Solution

In [41]:
rand_arr1[1::3]

array([[37, 27, 55, 20, 96, 95, 27, 79,  5, 14, 15, 81, 96, 44, 75, 24, 94,
        82, 15, 69],
       [17, 98, 41,  8,  9, 39, 11, 10, 56,  4,  2, 57, 10, 56, 96, 14, 38,
         9, 49, 15],
       [12, 75, 92, 20, 98, 80, 38, 23, 20, 88, 95, 62, 71, 79, 14, 98,  8,
        43, 55, 34],
       [23, 56, 36, 27, 16, 68, 48,  9, 28, 53, 57, 32, 30, 39, 83, 31, 25,
        28,  3, 86],
       [37,  5, 92,  4, 71, 10, 96, 69, 97, 28, 18, 86, 37, 73, 36, 97, 24,
        10, 12, 89],
       [41, 40, 24, 28, 57, 36, 72, 87, 82, 59, 82, 74, 15, 92, 64, 36, 48,
        73, 64, 42],
       [94, 75, 81, 60,  6, 33, 95, 61, 11, 41, 86, 16, 34, 85,  8, 58, 68,
        57, 98, 38]])

## Exercise Question #4

The result looks good. But looks like I dont need the row starting with 94..75.. Could you please eliminate that from your slice?

### Solution 

In [42]:
rand_arr1[1:-1:3]

array([[37, 27, 55, 20, 96, 95, 27, 79,  5, 14, 15, 81, 96, 44, 75, 24, 94,
        82, 15, 69],
       [17, 98, 41,  8,  9, 39, 11, 10, 56,  4,  2, 57, 10, 56, 96, 14, 38,
         9, 49, 15],
       [12, 75, 92, 20, 98, 80, 38, 23, 20, 88, 95, 62, 71, 79, 14, 98,  8,
        43, 55, 34],
       [23, 56, 36, 27, 16, 68, 48,  9, 28, 53, 57, 32, 30, 39, 83, 31, 25,
        28,  3, 86],
       [37,  5, 92,  4, 71, 10, 96, 69, 97, 28, 18, 86, 37, 73, 36, 97, 24,
        10, 12, 89],
       [41, 40, 24, 28, 57, 36, 72, 87, 82, 59, 82, 74, 15, 92, 64, 36, 48,
        73, 64, 42]])

In [44]:
rand_arr[:,::2] # Getting alternate columns .. The first colon before the comma represents all rows

array([[52, 13, 82],
       [73, 43, 52],
       [57, 82, 30],
       [75, 51, 98],
       [28,  8, 28],
       [55, 22, 17]])

In [4]:
chess_array = np.arange(64).reshape((8,8))

In [5]:
chess_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

Sometimes your array might be too big that you wont be able to print it entirely on the screen.
To print the  entire numpy array on screen without getting compressed.

In [8]:
np.set_printoptions(threshold=np.nan)

In [9]:
chess_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [10]:
chess_array[0::2,1::2] = 0

In [11]:
chess_array[1::2,0::2] = 0

In [12]:
chess_array[0::2,0::2] = 1

In [13]:
chess_array[1::2,1::2] = 1

In [14]:
chess_array

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### Broadcasting

In [15]:
# Lets create an array
a = np.array([1,2,34,5,563])

In [16]:
a

array([  1,   2,  34,   5, 563])

In [17]:
# Lets take a slice of a and assign it to b
b = a[2:5]

In [18]:
# Lets add an item to b's 0th index position
b[0] = 252

In [19]:
# But turns out a changed as well along with b
a

array([  1,   2, 252,   5, 563])

That is because slices are references and not separate objects and hence any change made through the references pointing to a slice of an array creates changes in the original array. This is called broadcasting.