In [1]:
import numpy as np

## Matrix Product
To find the matrix product, you use NumPy's matmul function.

If you have compatible shapes, then it's as simple as this:

In [2]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
a.shape

(2, 4)

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [5]:
b.shape

(4, 3)

Remember that for matrix multiplication to work, we need the number of rows in the first matrix equalling the number of columns of the second.

In [6]:
c = np.matmul(a, b)

In [7]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [8]:
c.shape

(2, 3)

If your matrices have incompatible shapes, you'll get an error, like the following:

In [9]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

## NumPy's dot function
Sometimes we may see NumPy's dot function in places where we would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.

So these two results are equivalent

In [10]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [12]:
a.dot(a)  # you can call `dot` directly on the `ndarray`

array([[ 7, 10],
       [15, 22]])

While these functions return the same results for two dimensional data, we should be careful about which we choose when working with other data shapes. 

## Transpose
Getting the transpose of a matrix is really easy in NumPy. Simply access its T attribute. There is also a transpose() function which returns the same thing, but you’ll rarely see that used anywhere because typing T is so much easier. :)

For example

In [14]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
m.T
# displays the following result:

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Something very important to learn about Numpy Transpose
NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it’s quite efficient.

However, that also means you need to be careful with how we modify objects, because they are sharing the same data. For example, with the same matrix m from above, let's make a new variable m_t that stores m's transpose. Then look what happens if we modify a value in m_t:

In [16]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [17]:
## Now lets look at m
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

Notice how it modified both the transpose and the original matrix, too! That's because they are sharing the same copy of data. So remember to consider the transpose just as a different view of your matrix, rather than a different matrix entirely.

## A real use case
Lets look at a little use case from neural networks because there is one place we will almost certainly end up using a transpose, or at least think about it.

Let's say we have the following two matrices, called inputs and weights,

In [19]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [20]:
inputs.shape
# displays the following result:

(1, 4)

In [21]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [22]:
weights.shape

(3, 4)

We are going to find the matrix product of these two matrices.

In [29]:
np.matmul(inputs, weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

From the matrix multiplication lesson, we know this error. It's complaining about incompatible shapes because the number of columns in the left matrix, 4, does not equal the number of rows in the right matrix, 3.

So that doesn't work, but notice if we take the transpose of the weights matrix, it will:

In [23]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [24]:
# It also works if we take the transpose of inputs instead and swap their order:

np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

The two answers are transposes of each other, so which multiplication you use really just depends on the shape you want for the output.