In [1]:
import numpy as np

In [2]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[3,6,7]]])

In [3]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 6, 7]]])

In [52]:
arr3d.T

array([[[1, 7],
        [4, 3]],

       [[2, 8],
        [5, 6]],

       [[3, 9],
        [6, 7]]])

In [54]:
arr1 = np.arange(16).reshape((2,2,4))

In [55]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
### Simple transpose with .T is just a special case of swapping axes.

### ndarray has the method swapaxes which takes a pair of axis numbers

arr1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [50]:
arr1.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [51]:
arr1.swapaxes(2,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
### swapaxes returns only a view and doesn't create a copy