In [3]:
import numpy as np

In [4]:
# Create a Boolean Numpy array
cond1 = np.array([True, False, True])

In [5]:
# Multiply it with 1
s = 1 * cond1

In [6]:
s

array([1, 0, 1])

In [7]:
cond2 = np.array([False, False, True])

In [8]:
# OR Operation
cond1 | cond2

array([ True, False,  True], dtype=bool)

In [9]:
# Inverse Operation
~ (cond1 | cond2)

array([False,  True, False], dtype=bool)

In [12]:
# Multiply 3 to the result
3 * ~ (cond1 | cond2)

array([0, 3, 0])

In [13]:
1 * cond1

array([1, 0, 1])

In [14]:
2 *  cond2

array([0, 0, 2])

In [15]:
3 * ~ (cond1 | cond2)

array([0, 3, 0])

In [11]:
# Lets put them all together
result = 1 * cond1 + 2 * cond2 + 3 * ~ (cond1 | cond2)

In [17]:
result

array([1, 3, 3])